#!/bin/bash

sudo dnf install -y \
  java-21-openjdk-devel \
  java-25-openjdk-devel

curl https://mise.run | sh

if ! grep -q "mise activate bash" ~/.bashrc; then
    echo "eval \"\$($HOME/.local/bin/mise activate bash)\"" >> ~/.bashrc
fi

. $HOME/.bashrc

mise link -f java@el-21 /usr/lib/jvm/java-21-openjdk
mise link -f java@el-25 /usr/lib/jvm/java-25-openjdk

mise plugin install maven
mise use -g maven@3
